ros_gz_bridge_node:
  ros__parameters:
    topics:
      - topic_name: "/clock"
        ros_type: "rosgraph_msgs/msg/Clock"
        gz_type: "gz.msgs.Clock"
        direction: "GZ_TO_ROS"

      - topic_name: "/scan"
        ros_type: "sensor_msgs/msg/LaserScan"
        gz_type: "gz.msgs.LaserScan"
        direction: "GZ_TO_ROS"

      - topic_name: "/camera_info"
        ros_type: "sensor_msgs/msg/CameraInfo"
        gz_type: "gz.msgs.CameraInfo"
        direction: "GZ_TO_ROS"

      - topic_name: "/depth_image"
        ros_type: "sensor_msgs/msg/Image"
        gz_type: "gz.msgs.Image"
        direction: "GZ_TO_ROS"

      - topic_name: "/image"
        ros_type: "sensor_msgs/msg/Image"
        gz_type: "gz.msgs.Image"
        direction: "GZ_TO_ROS"
