controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    mobile_base_controller:
      type: "diff_drive_controller/DiffDriveController"

    robotic_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

mobile_base_controller:
  ros__parameters:
    left_wheel_names: ["main_wheel_joint_left_to_main_wheel_left"]
    right_wheel_names: ["main_wheel_joint_right_to_main_wheel_right"]

    command_interfaces: ["velocity"]
    state_interfaces: ["position", "velocity"]

    wheel_separation: 0.5
    wheel_radius: 0.1
    cmd_vel_timeout: 0.5
    publish_rate: 50.0
    enable_odom_tf: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    use_sim_time: true

robotic_arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    state_publish_rate: 25
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true

    command_interfaces: ["position"]
    state_interfaces: ["position", "velocity"]

    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.01
      joint1: { trajectory: 0.1, goal: 0.1 }
      joint2: { trajectory: 0.1, goal: 0.1 }

joint_broad:
  ros__parameters:
    publish_rate: 50